### ISSUE TITLE
can not install tgintegration latest version 0.4.0 with pip

### ISSUE THREAD

**Issue by kevintruong** [JosXa/tgintegration#10]
* Python version: 3.8
* Operating System: ubuntu 18.04

### Description

Currenly, the latest version in pyi.python.org is 0.2.4 

Then all example will fail 
I trying install by clone your source code and manual install the latest version 0.4.0 

Would you please public release of 0.4.0 to pypi ? 
Thanks and best regards

**Comment by JosXa** [comment]
Hi @kevintruong, thanks for your issue and sorry for the late reply!

You are right, the library has not been maintained for a while - but I am getting back into it and updating it to the latest asyncio version of Pyrogram and looking to improve the design. Check back in a few days for a new release!

**Comment by JosXa** [comment]
https://github.com/JosXa/tgintegration/releases/tag/v1.0
Enjoy :)
