### ISSUE TITLE
Pressing the first keyboard button is not possible

### ISSUE THREAD

**Issue by hkoeck** [JosXa/tgintegration#2]
* tgintegration version: 0.2.4
* Python version: 3.6
* Operating System: Fedora 28

### Description

It is not possible to press the first button of a keyboard by using the index.
The check in keyboard.py:87 does evaluates to false if the index is 0

```
>>> index=0
>>> pattern=None
>>> any((pattern, index))
False
>>> index=1
>>> any((pattern, index))
True
```

### What I Did

```
response = inline_keyboard.press_button_await(index=0)
```
```
 ValueError: Exactly one of the `pattern` or `index` arguments must be provided.
```

**Comment by JosXa** [comment]
Hi @hkoeck, thanks for your bug report! I think you are right and this might still be an issue after the redesign.

- [ ] Add tests for this use case

**Comment by JosXa** [comment]
@hkoeck Could you check if this is still an issue on 1.0?
