### ISSUE TITLE
_raise=False failure to catch TimeoutError on python 3.7

### ISSUE THREAD

**Issue by Deer-Spangle** [JosXa/tgintegration#22]
* tgintegration version: 1.1.0
* Python version: 3.7
* Operating System: Linux

### Description

Running a test which is ensuring the bot does not respond, like so:
```
async with controller.collect(peer=group_id, raise_=False) as response:
    await controller.client.send_photo(group_id, thumb_link
assert response.num_messages == 0
````

### What I Did

It passes fine using python 3.8, but on python 3.7 it fails to catch the TimeoutError.
See this build log:
https://travis-ci.com/github/Deer-Spangle/FA-search-bot/jobs/439782520 for the full traceback

**Comment by Deer-Spangle** [comment]
This is no longer blocking me, as I have upgraded my dev machine, live environment, and CI builds to use Python 3.8

**Comment by JosXa** [comment]
3.7 has been deprecated.
