### ISSUE TITLE
keywords mismatch

### ISSUE THREAD

**Issue by StrangeTcy** [JosXa/tgintegration#9]
* tgintegration version: 0.4.0
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Description

Running the example script doesn't work, because a BotController from the README example expects `session_name`,`api_id` and `api_hash`, but the BotController as in currently is in the source file expects a `client` of the `InteractionClient` type and gets surprised by all the other keywords after the `bot_under_test`. 
To the best of my understanding, the idea is to create an `InteractionClient`, which uses pyrogram's `Client`, and pass all the keywords to it.
Interestingly, `BotIntegrationClient` from v 0.2.4 seemingly tries to do that.

**Comment by JosXa** [comment]
Yep, I'm aware of the issues and decided on a bigger rewrite a while ago (which isn't even halfway complete and kind of stuck in design), but my priorities lay elsewhere for the moment. If you push me enough, I might revive the project and 
But I would also like some input from the people interested in the library, so why don't you give me a ping at https://t.me/TgIntegration? :)

**Comment by JosXa** [comment]
https://github.com/JosXa/tgintegration/releases/tag/v1.0
Enjoy :)
